const t = require('tap')
const fs = require('fs')
const os = require('os')
const path = require('path')
const { spawnSync } = require('child_process')
const { publickeys } = require('@dotenvx/primitives')
const cli = path.resolve('src/cli/dotenvx.js')

t.test('encrypt, repeat encrypt, run and clean get output', t => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'dotenvx-summary-'))
  t.teardown(() => fs.rmSync(cwd, { recursive: true, force: true }))
  const env = { ...process.env, CI: 'true', DOTENVX_NO_NATIVE: 'true', DOTENVX_NO_ARMOR: 'true', DOTENVX_NO_1PASSWORD: 'true', DOTENVX_NO_BITWARDEN: 'true' }
  const run = args => spawnSync(process.execPath, [cli, ...args], { cwd, env, encoding: 'utf8' })
  fs.writeFileSync(path.join(cwd, '.env'), 'HELLO=World\n')
  fs.writeFileSync(path.join(cwd, '.env.production'), 'HI=There\n')
  const encrypted = run(['encrypt', '-f', '.env', '-f', '.env.production'])
  t.equal(encrypted.status, 0, encrypted.stderr)
  const files = ['.env', '.env.production'].map(file => `${file} (${publickeys(fs.readFileSync(path.join(cwd, file), 'utf8'))[0].slice(0, 6).toUpperCase().replace(/(.{3})(.{3})/, '$1 $2')})`).join(',')
  t.match(encrypted.stderr, `◈ encrypted ${files} via .env.keys ⛉`)
  const repeat = run(['encrypt', '-f', '.env', '-f', '.env.production'])
  t.equal(repeat.status, 0)
  t.match(repeat.stdout, `○ no change ${files} via .env.keys ⛉`)
  const injected = run(['run', '-f', '.env', '-f', '.env.production', '--', process.execPath, '-e', 'console.log(process.env.HELLO + process.env.HI)'])
  t.equal(injected.status, 0, injected.stderr)
  t.match(injected.stderr, files.split(',').join(', '))
  t.match(injected.stderr, 'via .env.keys ⛉')
  t.equal(injected.stdout.trim(), 'WorldThere')
  const get = run(['get', 'HELLO'])
  t.equal(get.status, 0)
  t.equal(get.stdout.trim(), 'World')
  const decrypted = run(['decrypt', '-f', '.env', '-f', '.env.production'])
  t.equal(decrypted.status, 0, decrypted.stderr)
  t.match(decrypted.stderr, `◇ decrypted ${files} via .env.keys ⛉`)
  t.match(fs.readFileSync(path.join(cwd, '.env'), 'utf8'), 'HELLO=World')
  t.match(fs.readFileSync(path.join(cwd, '.env.production'), 'utf8'), 'HI=There')
  t.end()
})
